### ISSUE TITLE
[error]Invalid Version: 1.2.6.1+ent

### ISSUE THREAD

**Issue by jkroepke** [innovationnorway/setup-vault#32]
Hi,

the action just throws an error:

```
Run innovationnorway/setup-vault@v1
  with:
    version: ~1.5
  env:
    SOPS_VERSION: 3.6.0
    DEVSCRIPTS_VERSION: 2.20.4
##[error]Invalid Version: 1.2.6.1+ent
```

**Comment by marcofranssen** [comment]
I got the same error. I also see the action was renamed recently from `volcano-coffee-company/setup-vault` to `innovationnorway/setup-vault`.

To me it seems the published action doesn't match the code in this repository.

**Comment by roberthstrand** [comment]
Looking into it now

**Comment by marcofranssen** [comment]
In this branch I also try locker the vault version at the patch level to see if that resolves the issue. 

https://github.com/philips-labs/dct-notary-admin/runs/1021204172?check_suite_focus=true

Unfortunately this also doesn't work.

Please note I do specify vault version 1.4.5 here but the error still mentions 1.2.6.1+ent.

**Comment by joakimhellum** [comment]
@marcofranssen 
1) HashiCorp recently started publishing enterprise versions here: https://releases.hashicorp.com/vault/
2) Some of these versions, like `1.2.6.1+ent`, is not a valid semantic version, and this is why you see the error:
```
##[error]Invalid Version: 1.2.6.1+ent
```
3) We (me and @roberthstrand) is working on a fix and expect to release it within next 4-8 hours.
About the latest version not being published to the Marketplace, sorry about that, we will fix it soon.
We will post update here within next few hours.

**Comment by joakimhellum** [comment]
Hi, this should be fixed in [`v1.0.2`](https://github.com/innovationnorway/setup-vault/releases/tag/v1.0.2) version - `v1` tag is also updated. sorry for the inconvenience

**Comment by marcofranssen** [comment]
@joakimhellum https://github.com/philips-labs/dct-notary-admin/runs/1022720169?check_suite_focus=true confirmed.

**Comment by Ameausoone** [comment]
good job 👍
