### ISSUE TITLE
No v1.0.1 on marketplace

### ISSUE THREAD

**Issue by jkroepke** [innovationnorway/setup-vault#33]
Hi,

on https://github.com/marketplace/actions/setup-vault there is no v1.0.1, but its a released version here.

**Comment by marcofranssen** [comment]
I also tried to upgrade to the new version, but it seems the marketplace doesn't have v1.0.1 there yet. Reason I wanted to upgrade is because of #32 

Would be great of one of the maintainers could have a look at both these issues.

**Comment by joakimhellum** [comment]
Hi, all Vault versions should be available in marketplace now. Sorry for the inconvenience. This repo was recently transferred and it seems the GitHub marketplace entry wasn't automatically updated to reflect the transfer.
